# Generated by Django 5.2.10 on 2026-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_player_time_of_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="percent_owned",
            field=models.IntegerField(default=0),
        ),
    ]
