# Generated by Django 4.2.6 on 2023-11-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_players_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='status',
            field=models.CharField(choices=[('gtd', 'GTD'), ('out', 'O'), ('injured', 'INJ'), ('healthy', 'H')], default='active', max_length=10),
        ),
    ]
